### ISSUE TITLE
Allow Custom KMS Key

### ISSUE THREAD

**Issue by xomgc3** [expel-io/terraform-aws-cloudtrail#50]
I see a variable for `existing_cloudtrail_kms_key_arn`.  However, it's not used if a new S3 bucket will be provisioned.  Additionally, the permissions for the key are not appropriate.

<img width="1040" alt="Screenshot 2023-10-23 at 9 40 48 AM" src="https://github.com/expel-io/terraform-aws-cloudtrail/assets/107490402/574af2e2-e6fb-4ba3-bcd0-9f88ed0e9c1a">

Please allow a custom Key ARN to take priority over a new key.  Adding a variable for a custom key policy could also be helpful.

**Comment by bachu20** [comment]
> I see a variable for `existing_cloudtrail_kms_key_arn`. However, it's not used if a new S3 bucket will be provisioned. Additionally, the permissions for the key are not appropriate.
> 
> <img alt="Screenshot 2023-10-23 at 9 40 48 AM" width="1040" src="https://user-images.githubusercontent.com/107490402/277376130-574af2e2-e6fb-4ba3-bcd0-9f88ed0e9c1a.png">
> Please allow a custom Key ARN to take priority over a new key. Adding a variable for a custom key policy could also be helpful.

Hey @xomgc3, had a few clarifying questions just to make sure I understand the use-case here.
- Do you just need a way to pass in a CMK key for use with the newly created SNS topic and/or SQS?
- If you can design a custom key would that be sufficient for your use-case? Would you still need a way to override the policy of a key we create if one isn't passed in?

**Comment by sarjumulmi** [comment]
> > I see a variable for `existing_cloudtrail_kms_key_arn`. However, it's not used if a new S3 bucket will be provisioned. Additionally, the permissions for the key are not appropriate.
> > <img alt="Screenshot 2023-10-23 at 9 40 48 AM" width="1040" src="https://user-images.githubusercontent.com/107490402/277376130-574af2e2-e6fb-4ba3-bcd0-9f88ed0e9c1a.png">
> > Please allow a custom Key ARN to take priority over a new key. Adding a variable for a custom key policy could also be helpful.
> 
> Hey @xomgc3, had a few clarifying questions just to make sure I understand the use-case here.
> 
> * Do you just need a way to pass in a CMK key for use with the newly created SNS topic and/or SQS?
> * If you can designate a custom key would that be sufficient for your use-case? Would you still need a way to override the policy of a key we create on your behalf otherwise?

@xomgc3 following up on @bachu20 Qs for some clarifications on our side.
